export default interface GameModel {
    GameEndDateTime: null,
    GameID: number,
    Season: number,
    SeasonType: number,
    Status: string,
    Day: string,
    DateTime: string,
    AwayTeam: string,
    HomeTeam: string,
    AwayTeamID: number,
    HomeTeamID: number,
    StadiumID: number,
    AwayTeamScore: null,
    HomeTeamScore: null,
    Updated: string,
    GlobalGameID: number,
    GlobalAwayTeamID: number,
    GlobalHomeTeamID: number,
    IsClosed: boolean,
    NeutralVenue: boolean,
    DateTimeUTC: string,
    SeriesInfo: null,
  }